name: style_hub
description: "Style Hub"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.5.1
  get_storage: ^2.1.1
  iconsax_plus: ^1.0.0
  share_plus: ^7.2.1
  flutter_svg: ^2.0.17
  flutter_carousel_slider: ^1.1.0
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
