import 'package:get/get.dart';

class AppLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'hello': 'Hello',
          'welcome': 'Welcome',
          'next': 'Next',
          'skip': 'Skip',
          'get_started': 'Get Started',
          'nearby_location': 'Nearby Your Location',
          'see_all': 'See All',
          'most_popular': 'Most Popular',
          'my_bookings': 'My Bookings',
          'profile': 'Profile',
          'edit_profile': 'Edit Profile',
          'notification': 'Notification',
          'payment': 'Payment',
          'security': 'Security',
          'language': 'Language',
          'dark_mode': 'Dark Mode',
          'privacy_policy': 'Privacy Policy',
          'invite_friends': 'Invite Friends',
          'logout': 'Logout',
          'select_language': 'Select Language',
          'logout_confirmation': 'Are you sure you want to logout?',
          'cancel': 'Cancel',
        },
        'uz_UZ': {
          'hello': 'Salom',
          'welcome': 'Xush kelibsiz',
          'next': 'Keyingisi',
          'skip': 'O\'tkazib yuborish',
          'get_started': 'Boshlash',
          'nearby_location': 'Yaqin manzildagilar',
          'see_all': 'Barchasi',
          'most_popular': 'Ommabop',
          'my_bookings': 'Mening jadvalim',
          'profile': 'Profil',
          'edit_profile': 'Profilni tahrirlash',
          'notification': 'Bildirishnomalar',
          'payment': 'To\'lov',
          'security': 'Xavfsizlik',
          'language': 'Til',
          'dark_mode': 'Qorong\'u rejim',
          'privacy_policy': 'Maxfiylik siyosati',
          'invite_friends': 'Do\'stlarni taklif qilish',
          'logout': 'Chiqish',
          'select_language': 'Tilni tanlang',
          'logout_confirmation': 'Tizimdan chiqishni xohlaysizmi?',
          'cancel': 'Bekor qilish',
        },
      };
}
